// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: psql.proto

package psql

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Table type enum
type TableType int32

const (
	TableType_DATA     TableType = 0
	TableType_RELATION TableType = 1
)

// Enum value maps for TableType.
var (
	TableType_name = map[int32]string{
		0: "DATA",
		1: "RELATION",
	}
	TableType_value = map[string]int32{
		"DATA":     0,
		"RELATION": 1,
	}
)

func (x TableType) Enum() *TableType {
	p := new(TableType)
	*p = x
	return p
}

func (x TableType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TableType) Descriptor() protoreflect.EnumDescriptor {
	return file_psql_proto_enumTypes[0].Descriptor()
}

func (TableType) Type() protoreflect.EnumType {
	return &file_psql_proto_enumTypes[0]
}

func (x TableType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TableType.Descriptor instead.
func (TableType) EnumDescriptor() ([]byte, []int) {
	return file_psql_proto_rawDescGZIP(), []int{0}
}

type CascadeUpdateOnRelatedTable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CascadeUpdateOnRelatedTable) Reset() {
	*x = CascadeUpdateOnRelatedTable{}
	mi := &file_psql_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CascadeUpdateOnRelatedTable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CascadeUpdateOnRelatedTable) ProtoMessage() {}

func (x *CascadeUpdateOnRelatedTable) ProtoReflect() protoreflect.Message {
	mi := &file_psql_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CascadeUpdateOnRelatedTable.ProtoReflect.Descriptor instead.
func (*CascadeUpdateOnRelatedTable) Descriptor() ([]byte, []int) {
	return file_psql_proto_rawDescGZIP(), []int{0}
}

func (x *CascadeUpdateOnRelatedTable) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *CascadeUpdateOnRelatedTable) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type RelayCascadeUpdate struct {
	state            protoimpl.MessageState            `protogen:"open.v1"`
	SourceForeignKey string                            `protobuf:"bytes,1,opt,name=source_foreign_key,json=sourceForeignKey,proto3" json:"source_foreign_key,omitempty"`
	Destinations     []*RelayCascadeUpdate_Destination `protobuf:"bytes,2,rep,name=destinations,proto3" json:"destinations,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RelayCascadeUpdate) Reset() {
	*x = RelayCascadeUpdate{}
	mi := &file_psql_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayCascadeUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayCascadeUpdate) ProtoMessage() {}

func (x *RelayCascadeUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_psql_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayCascadeUpdate.ProtoReflect.Descriptor instead.
func (*RelayCascadeUpdate) Descriptor() ([]byte, []int) {
	return file_psql_proto_rawDescGZIP(), []int{1}
}

func (x *RelayCascadeUpdate) GetSourceForeignKey() string {
	if x != nil {
		return x.SourceForeignKey
	}
	return ""
}

func (x *RelayCascadeUpdate) GetDestinations() []*RelayCascadeUpdate_Destination {
	if x != nil {
		return x.Destinations
	}
	return nil
}

type RelayCascadeUpdate_Destination struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ForeignKey    string                 `protobuf:"bytes,1,opt,name=foreign_key,json=foreignKey,proto3" json:"foreign_key,omitempty"`
	Field         string                 `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelayCascadeUpdate_Destination) Reset() {
	*x = RelayCascadeUpdate_Destination{}
	mi := &file_psql_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelayCascadeUpdate_Destination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelayCascadeUpdate_Destination) ProtoMessage() {}

func (x *RelayCascadeUpdate_Destination) ProtoReflect() protoreflect.Message {
	mi := &file_psql_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelayCascadeUpdate_Destination.ProtoReflect.Descriptor instead.
func (*RelayCascadeUpdate_Destination) Descriptor() ([]byte, []int) {
	return file_psql_proto_rawDescGZIP(), []int{1, 0}
}

func (x *RelayCascadeUpdate_Destination) GetForeignKey() string {
	if x != nil {
		return x.ForeignKey
	}
	return ""
}

func (x *RelayCascadeUpdate_Destination) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *RelayCascadeUpdate_Destination) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var file_psql_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: ([]string)(nil),
		Field:         1091,
		Name:          "psql.initialization",
		Tag:           "bytes,1091,rep,name=initialization",
		Filename:      "psql.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FileOptions)(nil),
		ExtensionType: ([]string)(nil),
		Field:         1092,
		Name:          "psql.finalization",
		Tag:           "bytes,1092,rep,name=finalization",
		Filename:      "psql.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*bool)(nil),
		Field:         1091,
		Name:          "psql.disabled",
		Tag:           "varint,1091,opt,name=disabled",
		Filename:      "psql.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: ([]string)(nil),
		Field:         1092,
		Name:          "psql.prefix",
		Tag:           "bytes,1092,rep,name=prefix",
		Filename:      "psql.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: ([]string)(nil),
		Field:         1093,
		Name:          "psql.suffix",
		Tag:           "bytes,1093,rep,name=suffix",
		Filename:      "psql.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: ([]string)(nil),
		Field:         1094,
		Name:          "psql.constraint",
		Tag:           "bytes,1094,rep,name=constraint",
		Filename:      "psql.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*TableType)(nil),
		Field:         1095,
		Name:          "psql.tableType",
		Tag:           "varint,1095,opt,name=tableType,enum=psql.TableType",
		Filename:      "psql.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: ([]*RelayCascadeUpdate)(nil),
		Field:         1096,
		Name:          "psql.relay_cascade_update",
		Tag:           "bytes,1096,rep,name=relay_cascade_update",
		Filename:      "psql.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         1091,
		Name:          "psql.column",
		Tag:           "bytes,1091,opt,name=column",
		Filename:      "psql.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         1092,
		Name:          "psql.auto_fill_on_update",
		Tag:           "bytes,1092,opt,name=auto_fill_on_update",
		Filename:      "psql.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: ([]*CascadeUpdateOnRelatedTable)(nil),
		Field:         1093,
		Name:          "psql.cascade_update_on_related_table",
		Tag:           "bytes,1093,rep,name=cascade_update_on_related_table",
		Filename:      "psql.proto",
	},
}

// Extension fields to descriptorpb.FileOptions.
var (
	// repeated string initialization = 1091;
	E_Initialization = &file_psql_proto_extTypes[0]
	// repeated string finalization = 1092;
	E_Finalization = &file_psql_proto_extTypes[1]
)

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional bool disabled = 1091;
	E_Disabled = &file_psql_proto_extTypes[2]
	// repeated string prefix = 1092;
	E_Prefix = &file_psql_proto_extTypes[3]
	// repeated string suffix = 1093;
	E_Suffix = &file_psql_proto_extTypes[4]
	// repeated string constraint = 1094;
	E_Constraint = &file_psql_proto_extTypes[5]
	// optional psql.TableType tableType = 1095;
	E_TableType = &file_psql_proto_extTypes[6]
	// repeated psql.RelayCascadeUpdate relay_cascade_update = 1096;
	E_RelayCascadeUpdate = &file_psql_proto_extTypes[7]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional string column = 1091;
	E_Column = &file_psql_proto_extTypes[8]
	// optional string auto_fill_on_update = 1092;
	E_AutoFillOnUpdate = &file_psql_proto_extTypes[9]
	// repeated psql.CascadeUpdateOnRelatedTable cascade_update_on_related_table = 1093;
	E_CascadeUpdateOnRelatedTable = &file_psql_proto_extTypes[10]
)

var File_psql_proto protoreflect.FileDescriptor

const file_psql_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"psql.proto\x12\x04psql\x1a google/protobuf/descriptor.proto\"I\n" +
	"\x1bCascadeUpdateOnRelatedTable\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xe8\x01\n" +
	"\x12RelayCascadeUpdate\x12,\n" +
	"\x12source_foreign_key\x18\x01 \x01(\tR\x10sourceForeignKey\x12H\n" +
	"\fdestinations\x18\x02 \x03(\v2$.psql.RelayCascadeUpdate.DestinationR\fdestinations\x1aZ\n" +
	"\vDestination\x12\x1f\n" +
	"\vforeign_key\x18\x01 \x01(\tR\n" +
	"foreignKey\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value*#\n" +
	"\tTableType\x12\b\n" +
	"\x04DATA\x10\x00\x12\f\n" +
	"\bRELATION\x10\x01:E\n" +
	"\x0einitialization\x12\x1c.google.protobuf.FileOptions\x18\xc3\b \x03(\tR\x0einitialization:A\n" +
	"\ffinalization\x12\x1c.google.protobuf.FileOptions\x18\xc4\b \x03(\tR\ffinalization:?\n" +
	"\bdisabled\x12\x1f.google.protobuf.MessageOptions\x18\xc3\b \x01(\bR\bdisabled\x88\x01\x01:8\n" +
	"\x06prefix\x12\x1f.google.protobuf.MessageOptions\x18\xc4\b \x03(\tR\x06prefix:8\n" +
	"\x06suffix\x12\x1f.google.protobuf.MessageOptions\x18\xc5\b \x03(\tR\x06suffix:@\n" +
	"\n" +
	"constraint\x12\x1f.google.protobuf.MessageOptions\x18\xc6\b \x03(\tR\n" +
	"constraint:R\n" +
	"\ttableType\x12\x1f.google.protobuf.MessageOptions\x18\xc7\b \x01(\x0e2\x0f.psql.TableTypeR\ttableType\x88\x01\x01:l\n" +
	"\x14relay_cascade_update\x12\x1f.google.protobuf.MessageOptions\x18\xc8\b \x03(\v2\x18.psql.RelayCascadeUpdateR\x12relayCascadeUpdate:9\n" +
	"\x06column\x12\x1d.google.protobuf.FieldOptions\x18\xc3\b \x01(\tR\x06column\x88\x01\x01:P\n" +
	"\x13auto_fill_on_update\x12\x1d.google.protobuf.FieldOptions\x18\xc4\b \x01(\tR\x10autoFillOnUpdate\x88\x01\x01:\x87\x01\n" +
	"\x1fcascade_update_on_related_table\x12\x1d.google.protobuf.FieldOptions\x18\xc5\b \x03(\v2!.psql.CascadeUpdateOnRelatedTableR\x1bcascadeUpdateOnRelatedTableB+Z)github.com/intrinsec/protoc-gen-psql/psqlb\x06proto3"

var (
	file_psql_proto_rawDescOnce sync.Once
	file_psql_proto_rawDescData []byte
)

func file_psql_proto_rawDescGZIP() []byte {
	file_psql_proto_rawDescOnce.Do(func() {
		file_psql_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_psql_proto_rawDesc), len(file_psql_proto_rawDesc)))
	})
	return file_psql_proto_rawDescData
}

var file_psql_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_psql_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_psql_proto_goTypes = []any{
	(TableType)(0),                         // 0: psql.TableType
	(*CascadeUpdateOnRelatedTable)(nil),    // 1: psql.CascadeUpdateOnRelatedTable
	(*RelayCascadeUpdate)(nil),             // 2: psql.RelayCascadeUpdate
	(*RelayCascadeUpdate_Destination)(nil), // 3: psql.RelayCascadeUpdate.Destination
	(*descriptorpb.FileOptions)(nil),       // 4: google.protobuf.FileOptions
	(*descriptorpb.MessageOptions)(nil),    // 5: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),      // 6: google.protobuf.FieldOptions
}
var file_psql_proto_depIdxs = []int32{
	3,  // 0: psql.RelayCascadeUpdate.destinations:type_name -> psql.RelayCascadeUpdate.Destination
	4,  // 1: psql.initialization:extendee -> google.protobuf.FileOptions
	4,  // 2: psql.finalization:extendee -> google.protobuf.FileOptions
	5,  // 3: psql.disabled:extendee -> google.protobuf.MessageOptions
	5,  // 4: psql.prefix:extendee -> google.protobuf.MessageOptions
	5,  // 5: psql.suffix:extendee -> google.protobuf.MessageOptions
	5,  // 6: psql.constraint:extendee -> google.protobuf.MessageOptions
	5,  // 7: psql.tableType:extendee -> google.protobuf.MessageOptions
	5,  // 8: psql.relay_cascade_update:extendee -> google.protobuf.MessageOptions
	6,  // 9: psql.column:extendee -> google.protobuf.FieldOptions
	6,  // 10: psql.auto_fill_on_update:extendee -> google.protobuf.FieldOptions
	6,  // 11: psql.cascade_update_on_related_table:extendee -> google.protobuf.FieldOptions
	0,  // 12: psql.tableType:type_name -> psql.TableType
	2,  // 13: psql.relay_cascade_update:type_name -> psql.RelayCascadeUpdate
	1,  // 14: psql.cascade_update_on_related_table:type_name -> psql.CascadeUpdateOnRelatedTable
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	12, // [12:15] is the sub-list for extension type_name
	1,  // [1:12] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_psql_proto_init() }
func file_psql_proto_init() {
	if File_psql_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_psql_proto_rawDesc), len(file_psql_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 11,
			NumServices:   0,
		},
		GoTypes:           file_psql_proto_goTypes,
		DependencyIndexes: file_psql_proto_depIdxs,
		EnumInfos:         file_psql_proto_enumTypes,
		MessageInfos:      file_psql_proto_msgTypes,
		ExtensionInfos:    file_psql_proto_extTypes,
	}.Build()
	File_psql_proto = out.File
	file_psql_proto_goTypes = nil
	file_psql_proto_depIdxs = nil
}
